import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import type { TanyaRunContext } from "../../context/runContext";
import { commitRequiredForRun } from "../git";
import { loadValidatorRules } from "./rules/load";
import type {
  BackendSetupEnvironmentRule,
  ValidatorRuleIssue,
  ValidatorRulePattern,
} from "./rules/types";

export type ValidationIssue = {
  id: string;
  severity: "error" | "warning";
  message: string;
  files?: string[];
  // When true, an unrepaired error flips the run VERDICT to FAIL (not just the
  // repair loop / footer). Reserved for objective, zero-false-positive static
  // checks (goose annotations, migration collision, localization parity) —
  // heuristic validators keep driving repair without gating the verdict.
  gating?: boolean;
};

export type ValidationSummary = {
  passed: boolean;
  issues: ValidationIssue[];
  firedValidatorIds?: string[];
  primaryPlatform?: "ios" | "macos" | "android" | "backend" | "landing" | "web" | "script" | "unknown";
};

export type ValidationManifest = {
  changedFiles: string[];
  artifactsRead?: string[];
  artifactsCreated?: string[];
  contextFilesRead?: string[];
  verification?: string[];
  blockers?: string[];
  git?: {
    root: string | null;
    head: string | null;
  };
  // HEAD at run start — baseline for diff-based reachability checks (deleted
  // analytics). Absent when the run had no starting commit.
  sessionBaseHead?: string;
};

export type Validator = {
  id: string;
  run(workspace: string, manifest: ValidationManifest, runContext?: TanyaRunContext): Promise<ValidationIssue[]> | ValidationIssue[];
};

export function taskText(runContext?: TanyaRunContext): string {
  return [
    runContext?.task?.title,
    runContext?.task?.summary,
    ...(runContext?.instructions ?? []),
  ].filter(Boolean).join("\n").toLowerCase();
}

export function constraintText(runContext?: TanyaRunContext): string {
  const rawPrompt = runContext?.metadata?.validationPrompt;
  return [
    taskText(runContext),
    typeof rawPrompt === "string" ? rawPrompt : null,
  ].filter(Boolean).join("\n").toLowerCase();
}

function metadataArray(runContext: TanyaRunContext | undefined, key: string): string[] {
  const value = runContext?.metadata?.[key];
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
}

function metadataBoolean(runContext: TanyaRunContext | undefined, key: string): boolean {
  const value = runContext?.metadata?.[key];
  return value === true || value === "true" || value === "yes";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function metadataRecord(runContext: TanyaRunContext | undefined, key: string): Record<string, unknown> | undefined {
  const value = runContext?.metadata?.[key];
  return isRecord(value) ? value : undefined;
}

function recordArray(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value) ? value.filter(isRecord) : [];
}

function autoBriefRecords(runContext: TanyaRunContext | undefined, key: string): Record<string, unknown>[] {
  return recordArray(metadataRecord(runContext, "autoBrief")?.[key]);
}

function hasExpectedReportFlag(runContext: TanyaRunContext | undefined, key: string): boolean {
  return runContext?.expected_report?.[key] === true;
}

export function uniqueSorted(values: Iterable<string>): string[] {
  return [...new Set([...values].filter(Boolean))].sort();
}

export function hasChanged(manifest: ValidationManifest, pattern: RegExp): boolean {
  return manifest.changedFiles.some((file) => pattern.test(file));
}

export function changedMatching(manifest: ValidationManifest, pattern: RegExp): string[] {
  return manifest.changedFiles.filter((file) => pattern.test(file));
}

export function hasSuccessfulVerification(manifest: ValidationManifest, pattern: RegExp): boolean {
  return (manifest.verification ?? []).some((line) =>
    pattern.test(line) &&
    /(?:->\s*passed|\bpassed\b|success marker found|shell exited 0|build succeeded)/i.test(line) &&
    !/->\s*failed\b/i.test(line)
  );
}

function hasSuccessfulCodegenVerification(manifest: ValidationManifest): boolean {
  return hasSuccessfulVerification(
    manifest,
    /\b(?:sqlc\s+generate|go\s+generate|buf\s+generate|protoc\b|prisma\s+generate|graphql-codegen|openapi-generator|swiftgen|xcodegen|make(?:\s+-C\s+\S+)?\s+gen)\b/i,
  );
}

function isGeneratedCodeHeader(text: string): boolean {
  return /\bCode generated by\b[\s\S]{0,300}\bDO NOT EDIT\b/i.test(text.slice(0, 2000));
}

async function validateGeneratedCodeProvenance(workspace: string, manifest: ValidationManifest): Promise<ValidationIssue[]> {
  if (hasSuccessfulCodegenVerification(manifest)) return [];
  const generatedFiles: string[] = [];
  for (const file of manifest.changedFiles) {
    const content = await readWorkspaceFile(workspace, file);
    if (content && isGeneratedCodeHeader(content)) generatedFiles.push(file);
  }
  if (generatedFiles.length === 0) return [];
  return [{
    id: "core-generated-code-without-generator-verification",
    severity: "error",
    message: "Changed files claim to be generated code, but no successful generator command was reported. Run the generator or remove the generated-code header; do not hand-write generated output.",
    files: generatedFiles.slice(0, 10),
  }];
}

export function isAppIconTask(text: string): boolean {
  return /\b(?:app icon|icon generation|launcher icon)\b/i.test(text) ||
    /\b(?:icone|ícone)\s+(?:do\s+)?app\b/i.test(text) ||
    /\bappicon\.appiconset\b/i.test(text) ||
    /\bic_launcher\b/i.test(text);
}

export function isApplePlatformTask(text: string): boolean {
  return /\b(?:ios|macos|apple|xcode|xcodebuild)\b/i.test(text) ||
    /\bappicon\.appiconset\b/i.test(text) ||
    /\bassets\.xcassets\b/i.test(text);
}

export function isAndroidPlatformTask(text: string): boolean {
  return /\bandroid\b/i.test(text) ||
    /\bic_launcher\b/i.test(text) ||
    /\bmipmap\b/i.test(text);
}

function normalizeSearchText(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

type PromptFeature = {
  name: string;
  tier: "free" | "premium" | "unknown";
};

export function extractPromptFeatures(text: string): PromptFeature[] {
  const features: PromptFeature[] = [];
  const seen = new Set<string>();
  for (const line of text.split(/\r?\n/)) {
    const match = line.match(/^\s*[-*]\s+\*\*(.+?)\*\*[\s\S]*?\[(premium|free)\]/i);
    if (!match) continue;
    const name = match[1]?.replace(/:\s*$/, "").trim();
    if (!name) continue;
    const key = normalizeSearchText(name);
    if (seen.has(key)) continue;
    seen.add(key);
    features.push({ name, tier: (match[2]?.toLowerCase() === "premium" ? "premium" : "free") });
  }
  return features;
}

function containsAny(haystack: string, words: string[]): boolean {
  return words.some((word) => {
    const normalized = normalizeSearchText(word);
    if (!normalized) return false;
    const escaped = normalized.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const pattern = new RegExp(`(?:^|[^a-z0-9])${escaped}`);
    return pattern.test(haystack);
  });
}

export function featureCoveredByText(feature: PromptFeature, implementationText: string): boolean {
  const name = normalizeSearchText(feature.name);
  const text = normalizeSearchText(implementationText);
  if (name.includes("perfi") && name.includes("juiz")) {
    return containsAny(text, ["perfil", "profile"]) &&
      containsAny(text, ["juiz", "juizes", "judge", "judges"]) &&
      containsAny(text, ["metrica", "metric", "performance"]);
  }
  if (name.includes("busca") || name.includes("jurisprudencia")) {
    return containsAny(text, ["busca", "search"]) &&
      containsAny(text, ["jurisprudencia", "decision", "decisao", "case", "cases", "juiz", "judge"]);
  }
  if (name.includes("alerta")) {
    return containsAny(text, ["alerta", "alert", "alerts", "notificacao", "notification"]);
  }
  if (name.includes("favorit") || name.includes("organiz")) {
    return containsAny(text, ["favorito", "favoritos", "favorite", "favorites", "organizacao", "organize"]);
  }
  if (name.includes("painel") || name.includes("dashboard")) {
    return containsAny(text, ["painel", "dashboard", "overview", "visao geral"]);
  }
  const meaningfulWords = name
    .split(/[^a-z0-9]+/i)
    .filter((word) => word.length >= 5 && !["feature", "modulo", "modulos", "sistema"].includes(word));
  if (meaningfulWords.length === 0) return true;
  return meaningfulWords.some((word) => containsAny(text, [word]));
}

export async function readWorkspaceFile(workspace: string, filePath: string): Promise<string | null> {
  try {
    return await readFile(join(workspace, filePath), "utf8");
  } catch {
    return null;
  }
}

export async function workspaceFileExists(workspace: string, filePath: string): Promise<boolean> {
  return (await readWorkspaceFile(workspace, filePath)) !== null;
}

export async function findWorkspaceFiles(
  workspace: string,
  predicate: (filePath: string) => boolean,
  options: { roots?: string[]; limit?: number } = {},
): Promise<string[]> {
  const roots = options.roots?.length ? options.roots : ["."];
  const limit = options.limit ?? 200;
  const results: string[] = [];
  const ignored = new Set([".git", ".gradle", ".tanya", "build", "DerivedData", "node_modules"]);

  async function walk(relativeDir: string) {
    if (results.length >= limit) return;
    let entries: Array<{ name: string; isDirectory(): boolean; isFile(): boolean }>;
    try {
      entries = await readdir(join(workspace, relativeDir), { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (results.length >= limit) return;
      const relativePath = relativeDir === "." ? entry.name : `${relativeDir}/${entry.name}`;
      if (entry.isDirectory()) {
        if (!ignored.has(entry.name)) await walk(relativePath);
        continue;
      }
      if (entry.isFile() && predicate(relativePath)) results.push(relativePath);
    }
  }

  for (const root of roots) await walk(root.replace(/\/$/, "") || ".");
  return results;
}

function pathMatchesPattern(filePath: string, pattern: string): boolean {
  const normalizedPattern = pattern.replace(/\\/g, "/");
  if (normalizedPattern.endsWith("/**")) {
    return filePath === normalizedPattern.slice(0, -3) || filePath.startsWith(normalizedPattern.slice(0, -2));
  }
  if (normalizedPattern.startsWith("**/*.")) {
    return filePath.endsWith(normalizedPattern.slice(4));
  }
  if (normalizedPattern.includes("*")) {
    const escaped = normalizedPattern
      .replace(/[.+?^${}()|[\]\\]/g, "\\$&")
      .replace(/\*\*/g, ".*")
      .replace(/\*/g, "[^/]*");
    return new RegExp(`^${escaped}$`).test(filePath);
  }
  return filePath === normalizedPattern || filePath.startsWith(`${normalizedPattern.replace(/\/$/, "")}/`);
}

function isForbiddenFile(filePath: string): boolean {
  const base = filePath.split("/").pop() ?? filePath;
  return base === "local.properties" ||
    /^\.env(?:\.|$)/.test(base) && base !== ".env.example" ||
    /\.(?:orig|bak|backup|tmp)$/i.test(base) ||
    filePath.includes("/.tanya/") ||
    filePath.startsWith(".tanya/");
}

function isTextFile(filePath: string): boolean {
  return /\.(?:ts|tsx|js|jsx|mjs|cjs|json|md|swift|kt|kts|gradle|rb|yml|yaml|xml|txt|env|example|properties|prisma)$/i.test(filePath);
}

export function isExplicitPlaceholderText(text: string): boolean {
  return /(?:\bexample\b|\bplaceholder\b|\bchange[\s_-]*me\b|\breplace[\s_-]*me\b|\bchangeme\b|\breplaceme\b|\byour[\s_-]+[a-z0-9_-]+|(?:^|[^a-z0-9])(?:REPLACE|CHANGE)_+[A-Z0-9_]+|xxxx|dummy|test[_-]?only|<[^>]+>)/i.test(text);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function issueFromRule(issue: ValidatorRuleIssue): ValidationIssue {
  return {
    id: issue.id,
    severity: issue.severity,
    message: issue.message,
    ...(issue.files ? { files: issue.files } : {}),
  };
}

function rulePatternMatches(text: string, pattern: ValidatorRulePattern): boolean {
  try {
    return new RegExp(pattern.pattern, pattern.flags).test(text);
  } catch {
    return false;
  }
}

function envValue(env: string, key: string): string {
  const match = env.match(new RegExp(`^${escapeRegExp(key)}\\s*=\\s*["']?([^"'\\n#]+)`, "m"));
  return match?.[1]?.trim() ?? "";
}

async function docTextForRule(
  workspace: string,
  rule: BackendSetupEnvironmentRule,
  fileCache: Map<string, string | null>,
): Promise<string> {
  const files = rule.docsFiles?.length ? rule.docsFiles : [rule.envFile ?? ".env.example"];
  const contents = await Promise.all(files.map(async (file) => {
    if (!fileCache.has(file)) fileCache.set(file, await readWorkspaceFile(workspace, file));
    return fileCache.get(file) ?? "";
  }));
  return contents.join("\n");
}

async function validateBackendSetupEnvironmentRule(
  workspace: string,
  rule: BackendSetupEnvironmentRule,
  fileCache: Map<string, string | null>,
): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const envFile = rule.envFile ?? ".env.example";
  if (!fileCache.has(envFile)) fileCache.set(envFile, await readWorkspaceFile(workspace, envFile));
  const env = fileCache.get(envFile);
  if (env == null) return issues;

  for (const requirement of rule.requiredEnv ?? []) {
    const value = envValue(env, requirement.name);
    if (!value) {
      issues.push(issueFromRule(requirement.missingIssue));
      continue;
    }
    for (const forbidden of requirement.forbiddenValues ?? []) {
      if (rulePatternMatches(value, forbidden)) {
        issues.push(issueFromRule(forbidden));
      }
    }
    const placeholder = requirement.placeholder;
    if (placeholder) {
      const explicitPlaceholderOk = placeholder.acceptedExplicitPlaceholder !== false && isExplicitPlaceholderText(value);
      const allowedPatternOk = (placeholder.allowedPatterns ?? []).some((pattern) => rulePatternMatches(value, pattern));
      if (!explicitPlaceholderOk && !allowedPatternOk) {
        issues.push(issueFromRule(placeholder.unclearIssue));
      }
    }
  }

  const docs = await docTextForRule(workspace, rule, fileCache);
  for (const requirement of rule.documentation ?? []) {
    const allMatched = (requirement.all ?? []).every((pattern) => rulePatternMatches(docs, pattern));
    const anyMatched = (requirement.any ?? []).length === 0 ||
      (requirement.any ?? []).some((pattern) => rulePatternMatches(docs, pattern));
    if (!allMatched || !anyMatched) {
      issues.push(issueFromRule(requirement.issue));
    }
  }

  return issues;
}

function looksLikeSecretLine(line: string): boolean {
  const match = line.match(/\b[A-Za-z0-9_-]*(?:api[_-]?key|secret|token|password|private[_-]?key|client[_-]?secret|database_url)[A-Za-z0-9_-]*\b\s*[:=]\s*["']?([^"',}\s]+)/i);
  if (!match) return false;
  const value = match[1] ?? "";
  if (isExplicitPlaceholderText(value)) return false;
  if (/^(?:process\.env\.|state\.|data\.|[\w$]+\.)/.test(value)) return false;
  // Pure-letters bare identifier (camelCase variable reference) — almost
  // always a code symbol, not a literal secret. Real secrets contain digits OR
  // underscores OR other separators (Stripe `sk_live_...`, AWS `AKIA...`, JWT `.`).
  // 2026-05-01 Cosa Nostra audit: `val pendingToken = pendingGoogleIdToken` tripped
  // this rule because pendingGoogleIdToken is 22 chars alnum.
  if (/^[A-Za-z_$][A-Za-z]*$/.test(value)) return false;
  return /^[A-Za-z0-9_./+=-]{16,}$/.test(value);
}

function commandKey(command: string): string {
  return command
    .replace(/^Verification:\s*/i, "")
    .replace(/\s*->.*$/, "")
    .replace(/\s+/g, " ")
    .trim();
}

function capturedSatisfiesRequested(captured: string[], requested: string): boolean {
  const normalizedRequested = requested.trim().replace(/\s+/g, " ");
  if (captured.includes(normalizedRequested)) return true;
  const escaped = normalizedRequested.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(`(?:^|[\\s;|&])${escaped}(?=$|[\\s;|&]|2>&1|>>?\\s|<\\s)`, "i");
  return captured.some((line) => pattern.test(line));
}

function isExactRequiredVerificationCommand(command: string): boolean {
  return /^(?:npm|pnpm|yarn|bun)\s+(?:install|ci|test|run\s+[\w:-]+)\b/i.test(command) ||
    /^npx\s+[\w@./:-]+/i.test(command) ||
    /^\.\/gradlew\s+[\w:-]+/i.test(command) ||
    /^xcodebuild\s+(?:build|test|archive|-list)\b/i.test(command);
}

function exactVerificationCommandsRequired(runContext: TanyaRunContext | undefined): boolean {
  if (metadataBoolean(runContext, "exactVerificationCommands") || metadataBoolean(runContext, "strictVerificationCommands")) {
    return true;
  }
  return runContext?.metadata?.caller !== "cosmochat";
}

export const coreValidators: Validator[] = [
  {
    id: "core.scope.forbiddenFiles",
    run(_workspace, manifest) {
      return manifest.changedFiles
        .filter(isForbiddenFile)
        .map((file) => ({
          id: "core-scope-forbidden-file",
          severity: "error",
          message: `Changed forbidden or generated file: ${file}`,
          files: [file],
        }));
    },
  },
  {
    id: "core.generatedCode.provenance",
    run(workspace, manifest) {
      return validateGeneratedCodeProvenance(workspace, manifest);
    },
  },
  {
    id: "core.scope.allowedPaths",
    run(_workspace, manifest, runContext) {
      const allowedPaths = metadataArray(runContext, "allowedPaths");
      if (allowedPaths.length === 0) return [];
      return manifest.changedFiles
        .filter((file) => !allowedPaths.some((pattern) => pathMatchesPattern(file, pattern)))
        .map((file) => ({
          id: "core-scope-outside-allowed-paths",
          severity: "error",
          message: `Changed file outside configured allowed paths: ${file}`,
          files: [file],
        }));
    },
  },
  {
    id: "core.artifact.provenance",
    run(_workspace, manifest, runContext) {
      if (!hasExpectedReportFlag(runContext, "artifact_reuse")) return [];
      const availableArtifacts = runContext?.artifacts?.filter((artifact) => artifact.status !== "missing") ?? [];
      if (availableArtifacts.length === 0) return [];
      if ((manifest.artifactsRead ?? []).length > 0 || (manifest.artifactsCreated ?? []).length > 0) return [];
      return [{
        id: "core-artifact-provenance-missing",
        severity: "error",
        message: "Caller supplied artifacts and required artifact provenance, but no artifact was read or created.",
      }];
    },
  },
  {
    id: "core.autoBrief.artifactConsideration",
    run(_workspace, manifest, runContext) {
      if (!metadataBoolean(runContext, "autoBriefEnforceArtifacts")) return [];
      if (manifest.changedFiles.length === 0) return [];
      if (autoBriefRecords(runContext, "artifacts").length === 0) return [];
      if ((manifest.artifactsRead ?? []).length > 0 || (manifest.artifactsCreated ?? []).length > 0) return [];
      return [{
        id: "core-auto-brief-artifact-not-considered",
        severity: "error",
        message: "Automatic task brief found reusable artifact candidates, but no artifact was read or created before changing files.",
      }];
    },
  },
  {
    id: "core.context.review",
    run(_workspace, manifest, runContext) {
      const hasContextToReview = hasExpectedReportFlag(runContext, "context_review") ||
        autoBriefRecords(runContext, "contextFiles").length > 0 ||
        (runContext?.contextFiles ?? []).length > 0;
      if (!hasContextToReview) return [];
      if (manifest.changedFiles.length === 0) return [];
      if ((manifest.contextFilesRead ?? []).length > 0) return [];
      return [{
        id: "core-context-review-missing",
        severity: "warning",
        message: "Automatic task brief found context files, but none were read before changing files.",
      }];
    },
  },
  {
    id: "core.verification.executed",
    run(_workspace, manifest, runContext) {
      if (!hasExpectedReportFlag(runContext, "verification")) return [];
      const verification = manifest.verification ?? [];
      if (verification.length === 0) {
        return [{ id: "core-verification-missing", severity: "error", message: "Expected verification, but no verification command was captured." }];
      }
      const requested = runContext?.verification?.commands ?? [];
      const passedKeys = verification
        .filter((line) => /->\s*passed\b/i.test(line))
        .map(commandKey);
      const strictRequestedCommands = exactVerificationCommandsRequired(runContext);
      return requested
        .filter((command) => !capturedSatisfiesRequested(passedKeys, command))
        .map((command) => ({
          id: "core-verification-requested-command-missing",
          severity: strictRequestedCommands && isExactRequiredVerificationCommand(command) ? "error" : "warning",
          message: `Requested verification command was not captured exactly: ${command}`,
        }));
    },
  },
  {
    id: "core.git.commit",
    run(_workspace, manifest, runContext) {
      if (manifest.changedFiles.length === 0) return [];
      // Mirror the runner's gate: ad-hoc runs (no runContext) require a commit
      // by default; pipeline runs keep the opt-in flags; explicit opt-out wins.
      if (!commitRequiredForRun(runContext, true)) return [];
      if (manifest.git?.head) return [];
      return [{ id: "core-git-commit-missing", severity: "error", message: "A commit was required, but no git HEAD was captured." }];
    },
  },
  {
    id: "core.secrets.noLeak",
    async run(workspace, manifest) {
      const issues: ValidationIssue[] = [];
      for (const file of manifest.changedFiles.filter(isTextFile)) {
        const content = await readWorkspaceFile(workspace, file);
        if (!content) continue;
        const lineNumber = content.split(/\r?\n/).findIndex(looksLikeSecretLine);
        if (lineNumber >= 0) {
          issues.push({
            id: "core-secrets-possible-leak",
            severity: "error",
            message: `Possible hardcoded secret in ${file}:${lineNumber + 1}`,
            files: [file],
          });
        }
      }
      return issues;
    },
  },
];

export function looksLikeCtaTitle(value: string): boolean {
  return /\b(?:começar|comecar|comece|começo|comeco|pronto|vamos|conta|grátis|gratis|cta|iniciar|start|get started|unlock|desbloquear)\b/i.test(value);
}

export function hasDedicatedCtaSlide(content: string, platform: "ios" | "android"): boolean {
  if (/\b(?:isCta|isCTA|cta|finalSlide|FinalSlide|OnboardingCta|CTA)\b/.test(content)) return true;
  const titles = platform === "ios"
    ? [...content.matchAll(/title:\s*"([^"]+)"/g)].map((match) => match[1] ?? "")
    : [...content.matchAll(/title\s*=\s*"([^"]+)"/g)].map((match) => match[1] ?? "");
  if (titles.length === 0) return /\bComeçar grátis\b[\s\S]*\bJá tenho conta\b/.test(content);
  const lastTitle = titles[titles.length - 1] ?? "";
  return looksLikeCtaTitle(lastTitle);
}

export async function validateSetupEnvironment(workspace: string, manifest: ValidationManifest, runContext?: TanyaRunContext): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const text = taskText(runContext);
  if (/\bios\b/.test(text)) {
    const fastlaneFiles = changedMatching(manifest, /(?:^|\/)fastlane\/Fastfile$/);
    const swiftLintFiles = changedMatching(manifest, /(?:^|\/)\.swiftlint\.yml$/);
    if (fastlaneFiles.length === 0) {
      issues.push({ id: "setup-ios-fastlane-missing", severity: "error", message: "iOS setup must create or update fastlane/Fastfile." });
    }
    if (swiftLintFiles.length === 0) {
      issues.push({ id: "setup-ios-swiftlint-missing", severity: "error", message: "iOS setup must create or update .swiftlint.yml." });
    }
    for (const file of fastlaneFiles) {
      const content = await readWorkspaceFile(workspace, file);
      if (content && !/\blane\s+:build\b/.test(content)) {
        issues.push({ id: "setup-ios-fastlane-build-lane-missing", severity: "error", message: "Fastfile must define a build lane.", files: [file] });
      }
    }
  }
  if (/\bandroid\b/.test(text)) {
    const gradleFiles = changedMatching(manifest, /(?:^|\/)(?:build\.gradle\.kts|build\.gradle|libs\.versions\.toml|settings\.gradle\.kts)$/);
    if (gradleFiles.length === 0) {
      issues.push({ id: "setup-android-gradle-missing", severity: "error", message: "Android setup must update Gradle project configuration." });
    }
    for (const file of gradleFiles) {
      const content = await readWorkspaceFile(workspace, file);
      if (content && /compileSdk\s*(?:=|\()\s*(\d+)/.test(content)) {
        const compileSdk = Number(content.match(/compileSdk\s*(?:=|\()\s*(\d+)/)?.[1]);
        if (compileSdk < 35) issues.push({ id: "setup-android-compile-sdk-low", severity: "error", message: "compileSdk must be at least 35.", files: [file] });
      }
    }
  }
  return issues;
}

export async function validateApiClient(workspace: string, manifest: ValidationManifest): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const clientFiles = changedMatching(manifest, /(?:ApiClient|APIClient|ApiRepository|APIRepository|Repository).*\.(?:swift|kt|ts)$/);
  if (clientFiles.length === 0) {
    return [{ id: "api-client-files-missing", severity: "error", message: "API client/repository task did not modify a recognizable client or repository file." }];
  }
  for (const file of clientFiles) {
    const content = await readWorkspaceFile(workspace, file);
    if (!content) continue;
    if (!/\bhttps?:\/\/|baseURL|baseUrl|BASE_URL|URLSession|OkHttp|Retrofit|fetch\(/.test(content)) {
      issues.push({ id: "api-client-base-url-missing", severity: "warning", message: "Could not confirm base URL or HTTP client wiring.", files: [file] });
    }
    if (!/\basync\b|suspend\s+fun|URLSession|OkHttp|Retrofit|fetch\(/.test(content)) {
      issues.push({ id: "api-client-async-flow-missing", severity: "warning", message: "Could not confirm async API call handling.", files: [file] });
    }
  }
  return issues;
}

export async function validateAuthSession(workspace: string, manifest: ValidationManifest): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const authFiles = changedMatching(manifest, /(?:Auth|Session|Token|Keychain|SecureStorage|DataStore).*\.(?:swift|kt|ts)$/);
  if (authFiles.length === 0) {
    return [{ id: "auth-session-files-missing", severity: "error", message: "Auth/session task did not modify a recognizable auth, session, token, or secure storage file." }];
  }
  for (const file of authFiles) {
    const content = await readWorkspaceFile(workspace, file);
    if (!content) continue;
    if (/UserDefaults|SharedPreferences/.test(content) && !/Keychain|EncryptedSharedPreferences|DataStore|Secure/i.test(content)) {
      issues.push({ id: "auth-session-insecure-storage", severity: "error", message: "Auth tokens must not be stored in plain UserDefaults or SharedPreferences.", files: [file] });
    }
    if (/\b(?:token|jwt|accessToken|refreshToken)\b/i.test(content) && !/logout|signOut|clear/i.test(content)) {
      issues.push({ id: "auth-session-clear-missing", severity: "warning", message: "Token/session code should include a clear/logout path.", files: [file] });
    }
  }
  return issues;
}

export async function validateBackendHealthApi(workspace: string, manifest: ValidationManifest, runContext?: TanyaRunContext): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const backendFiles = changedMatching(manifest, /(?:^|\/)(?:src\/|routes\/|server\/|prisma\/|backend\/).*\.(?:ts|js|mjs|prisma|md)$/);
  if (backendFiles.length === 0) {
    return [{ id: "backend-api-files-missing", severity: "error", message: "Backend/API task did not modify recognizable backend files." }];
  }
  const combined = (await Promise.all(backendFiles.slice(0, 40).map(async (file) => await readWorkspaceFile(workspace, file) ?? ""))).join("\n");
  if (/\bhealth\b/i.test(taskText(runContext)) && !/health|status|ready/i.test(combined)) {
    issues.push({ id: "backend-health-route-missing", severity: "warning", message: "Could not confirm a health/status endpoint in backend changes.", files: backendFiles.slice(0, 5) });
  }
  if (/process\.env\.[A-Z0-9_]+/.test(combined) && !manifest.changedFiles.some((file) => /(?:^|\/)\.env\.example$|EnvExample/i.test(file))) {
    issues.push({ id: "backend-env-example-missing", severity: "warning", message: "Backend task references env vars but did not update .env.example or an env artifact.", files: backendFiles.slice(0, 5) });
  }
  return issues;
}

export async function validateBackendSetupEnvironment(workspace: string): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const env = await readWorkspaceFile(workspace, ".env.example");

  if (!env) {
    return [{
      id: "backend-setup-env-example-missing",
      severity: "error",
      message: "Backend setup must create or update .env.example with safe placeholders.",
      files: [".env.example"],
    }];
  }

  const fileCache = new Map<string, string | null>([[".env.example", env]]);
  for (const rule of loadValidatorRules().filter((item): item is BackendSetupEnvironmentRule => item.kind === "backend_setup_environment")) {
    issues.push(...await validateBackendSetupEnvironmentRule(workspace, rule, fileCache));
  }

  return issues;
}

export async function validateRevenueCat(workspace: string, manifest: ValidationManifest): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];
  const files = changedMatching(manifest, /(?:RevenueCat|Paywall|Subscription|Premium|Entitlement|Purchases|Webhook).*\.(?:swift|kt|ts|js)$/);
  if (files.length === 0) {
    return [{ id: "revenuecat-files-missing", severity: "error", message: "RevenueCat task did not modify recognizable RevenueCat, paywall, subscription, premium, entitlement, or webhook files." }];
  }
  const combined = (await Promise.all(files.map(async (file) => await readWorkspaceFile(workspace, file) ?? ""))).join("\n");
  if (!/RevenueCat|Purchases|entitlement|paywall|subscription|webhook/i.test(combined)) {
    issues.push({ id: "revenuecat-wiring-missing", severity: "error", message: "Could not confirm RevenueCat/paywall/subscription wiring.", files });
  }
  if (/api[_-]?key|secret|token/i.test(combined) && /["'][A-Za-z0-9_./+=-]{16,}["']/.test(combined) && !/process\.env|\$\{|BuildConfig|Info\.plist|Environment/i.test(combined)) {
    issues.push({ id: "revenuecat-hardcoded-secret-risk", severity: "error", message: "RevenueCat credentials appear hardcoded instead of environment/config driven.", files });
  }
  return issues;
}

export function inferPrimaryPlatform(workspace: string): ValidationSummary["primaryPlatform"] {
  const m = workspace.toLowerCase().match(/\/(ios|macos|android|backend|landing|web|script|cli)(?:\/|$)/);
  if (!m) return "unknown";
  // cli → script: workspace folders are sometimes named cli/, treat them as script.
  return m[1] === "cli" ? "script" : (m[1] as ValidationSummary["primaryPlatform"]);
}
