// Generated-project detection for the build-before-new-files nudge (PROMPT B2
// item 3). In a repo whose Xcode project is GENERATED (xcodegen from
// project.yml, tuist from Project.swift), a brand-new source file is invisible
// to the build until the generator reruns — the audited run created 6 new
// .swift files, never ran `xcodegen generate`, and the first (never-run) build
// would have failed on all of them. Detection is a small extensible table of
// root markers; keep entries cheap (existsSync only, cached per run).

import { existsSync } from "node:fs";
import { join } from "node:path";

export type ProjectGenerator = {
  id: string;
  // Root file whose presence means the project is generated by this tool.
  marker: string;
  // The command that must run so the build sees new files.
  regenCommand: string;
  // Only files matching this pattern are project members the generator tracks.
  sourcePattern: RegExp;
};

export const PROJECT_GENERATORS: ProjectGenerator[] = [
  { id: "xcodegen", marker: "project.yml", regenCommand: "xcodegen generate", sourcePattern: /\.(swift|m|mm|h)$/i },
  { id: "tuist", marker: "Project.swift", regenCommand: "tuist generate", sourcePattern: /\.(swift|m|mm|h)$/i },
];

/** The generator managing this workspace, or null. First match wins. */
export function detectProjectGenerator(workspace: string): ProjectGenerator | null {
  for (const generator of PROJECT_GENERATORS) {
    if (existsSync(join(workspace, generator.marker))) return generator;
  }
  return null;
}
